# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"term": "00_ghtop.ipynb",
         "logfile": "00_ghtop.ipynb",
         "github_auth_device": "00_ghtop.ipynb",
         "exit": "00_ghtop.ipynb",
         "get_token": "00_ghtop.ipynb",
         "limit_cb": "00_ghtop.ipynb",
         "fetch_events": "00_ghtop.ipynb",
         "read_json_log": "00_ghtop.ipynb",
         "Events": "00_ghtop.ipynb",
         "printed_event_ids": "00_ghtop.ipynb",
         "to_log": "00_ghtop.ipynb",
         "print_event": "00_ghtop.ipynb",
         "write_logs": "00_ghtop.ipynb",
         "tail_events": "00_ghtop.ipynb",
         "watch_users": "00_ghtop.ipynb",
         "push_to_log": "00_ghtop.ipynb",
         "str_clean": "00_ghtop.ipynb",
         "signal_handler": "00_ghtop.ipynb",
         "quad_logs": "00_ghtop.ipynb",
         "simple": "00_ghtop.ipynb",
         "help_msg": "00_ghtop.ipynb",
         "mode_map": "00_ghtop.ipynb"}

modules = ["ghtop.py"]

doc_url = "https://fastai.github.io/ghtop/"

git_url = "https://github.com/fastai/ghtop/tree/master/"

def custom_doc_links(name): return None
