# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"border_bl": "00_dashing.ipynb",
         "border_br": "00_dashing.ipynb",
         "border_tl": "00_dashing.ipynb",
         "border_tr": "00_dashing.ipynb",
         "border_h": "00_dashing.ipynb",
         "border_v": "00_dashing.ipynb",
         "hbar_elements": "00_dashing.ipynb",
         "vbar_elements": "00_dashing.ipynb",
         "braille_left": "00_dashing.ipynb",
         "braille_right": "00_dashing.ipynb",
         "braille_r_left": "00_dashing.ipynb",
         "braille_r_right": "00_dashing.ipynb",
         "TBox": "00_dashing.ipynb",
         "Tile": "00_dashing.ipynb",
         "Split": "00_dashing.ipynb",
         "VSplit": "00_dashing.ipynb",
         "HSplit": "00_dashing.ipynb",
         "Text": "00_dashing.ipynb",
         "Log": "00_dashing.ipynb",
         "HGauge": "00_dashing.ipynb",
         "VGauge": "00_dashing.ipynb",
         "ColorRangeVGauge": "00_dashing.ipynb",
         "VChart": "00_dashing.ipynb",
         "HChart": "00_dashing.ipynb",
         "HBrailleChart": "00_dashing.ipynb",
         "HBrailleFilledChart": "00_dashing.ipynb",
         "term": "01_ghtop.ipynb",
         "logfile": "01_ghtop.ipynb",
         "url": "01_ghtop.ipynb",
         "github_auth_device": "01_ghtop.ipynb",
         "get_token": "01_ghtop.ipynb",
         "token": "01_ghtop.ipynb",
         "fetch_events": "01_ghtop.ipynb",
         "read_json_log": "01_ghtop.ipynb",
         "printed_event_ids": "01_ghtop.ipynb",
         "wait_for_event": "01_ghtop.ipynb",
         "wait_for_event.time_pointer": "01_ghtop.ipynb",
         "print_event": "01_ghtop.ipynb",
         "write_logs": "01_ghtop.ipynb",
         "tail_events": "01_ghtop.ipynb",
         "watch_users": "01_ghtop.ipynb",
         "push_to_log": "01_ghtop.ipynb",
         "issue_to_log": "01_ghtop.ipynb",
         "pr_to_log": "01_ghtop.ipynb",
         "release_to_log": "01_ghtop.ipynb",
         "str_clean": "01_ghtop.ipynb",
         "signal_handler": "01_ghtop.ipynb",
         "quad_logs": "01_ghtop.ipynb",
         "simple": "01_ghtop.ipynb"}

modules = ["dashing.py",
           "ghtop.py"]

doc_url = "https://fastai.github.io/ghtop/"

git_url = "https://github.com/fastai/ghtop/tree/master/"

def custom_doc_links(name): return None
